### ISSUE TITLE
Getting erros when comitting outside of Git CLI

### ISSUE THREAD

**Issue by Ahrengot** [therealklanni/git-guppy#38] opened 2015-09-25 11:23 UTC
Great plugin! Really easy to use.

It works as expected when I commit through the terminal:
![terminal commit](https://s3.amazonaws.com/f.cl.ly/items/292o3J0z331d1D0v3M0d/Image%202015-09-25%20at%201.18.38%20PM.png)

However if I commit using the git plugin in Sublime Text or via [Sourcetree](https://www.sourcetreeapp.com/) I get the following error:

    git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F 
    /var/folders/gm/gfdrphq92hlb_254_lglh2gc0000gn/T/SourceTreeTemp.NNOSXH 
    env: node: No such file or directory
    Completed with errors, see above

I'm sure this is just an issue with my setup, but I'm curious to see if you have any insight into what might be going on and anything I could change hoping to fix this.

Thanks in advance.

**Comment by Ahrengot** [comment] 2015-09-25 19:52
Turns out my error was caused by a missing symlink. See first answer here http://stackoverflow.com/questions/20061529/sublime-text-coffeescript-build-system-env-node-no-such-file-or-directory for anyone with the same issue.

Now the second issue is that the following snippet will only block the commit if I commit through the command line and not through source tree or the sublime git plugin:

    gulp.task('pre-commit', guppy.src('pre-commit', function(filesChanged) {
      console.log( chalk.green("\n\Hold on buddy — Let me check if you messed up before accepting your commit   ") + chalk.yellow(cool()) + "\n\n" );
      return gulp.src(filesChanged)
      .pipe( $.filter('*.js') )
      .pipe( $.jshint() )
      .pipe( $.jshint.reporter('jshint-stylish') )
      .pipe( $.jshint.reporter('error') )
      .pipe(jshint.reporter('fail'))
    }));

I wonder if this is again something on my end, or this is a limitation with the tool. hmmm?

**Comment by therealklanni** [comment] 2015-09-26 10:00
The solution you found would definitely work, however—at least in OS X—I found that this can also be resolved by simply having your paths set in the right order.

It's definitely not a limitation with the tool (perhaps a bug, if not something to do with your system), it should work with any third-party app. For instance, it works in the GitHub desktop app.

If you can post your `$PATH` env var and your path to node (`which node`), that may give us some insight.

**Comment by Ahrengot** [comment] 2015-09-26 11:37
Hey @therealklanni thanks for getting back to me. 

My node is at `/usr/local/bin/node` but the symlink makes sure `/usr/bin/node` points to the same place so that's now working. I think there's some other funky thing going on. I found this pre-commit script elsewhere and it successfully triggers the `lint-js` gulp task I've set up.

```bash
#!/bin/sh

if git diff --cached --name-only --diff-filter=ACM | grep '.js$' >/dev/null 2>&1
then
  ./node_modules/.bin/gulp lint-js
fi

exit $?
```

The problem is of course that git hooks aren't committed and I can't easily install this hook on other machines without sending them this snippet. That's what's so great about your npm module.

Any thoughts on what might be causing this script to work across all apps my machine and the git-guppy to fail outside of the command line?

**Comment by therealklanni** [comment] 2015-09-27 02:28
It has to have something to do with the environment that the 3rd-party app runs the git command in. If the environment has trouble seeing the gulp exit status properly, that would cause it to not prevent the commit.

Can you point me to your gulpfile (or paste relevant snippet here)? It would also be helpful to see the output of your `git commit` attempt and `echo $?` afterward from commandline. As well as any log/output/error from the 3rd-party app that you might be getting.

**Comment by therealklanni** [comment] 2015-09-27 02:42
OK, forgot that you posted the original SourceTree error message. That's a common issue. Do you get something different since creating that link? I strongly suspect the problem is deeper than simply linking the `node` executable, though. 

A better solution may be to get your PATH env var set correctly, I think. Which operating system is it, by the way? Looks like OS X, but I can't be sure.

**Comment by Ahrengot** [comment] 2015-09-28 15:40
Thanks for taking the time to help out here. I really appreciate it.

Yep, I'm using OSX 10.10.5 (Yosimite)

I set up a reduced test case that I can commit fine in Source Tree but breaks as expected when committing through the command line: https://github.com/Ahrengot/test-precommit

You mention setting up the PATH env correctly. I don't really know how to mess around with that stuff — Can you point me in a direction of a guide of some sort?

**Comment by nastiatikk** [comment] 2015-10-08 19:57
Just a note that I am experiencing the same issues and SourceTree is not able to handle the pre-commit script

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/qn/3lmq_g9s21bf7fl_p8fr5d4m0000gn/T/SourceTreeTemp.TGwKAo 
env: node: No such file or directory
Completed with errors, see above
```

**Comment by therealklanni** [comment] 2015-10-08 23:37
@nastiatikk you need to set your environment (i.e. PATH) properly.

Follow the instructions here for setting your PATH using `/etc/paths`: http://superuser.com/a/533708

Let me know if this resolves it for you both.

**Comment by nastiatikk** [comment] 2015-10-13 04:22
@therealklanni Thank you Kevin, it resolved my issue!

**Comment by therealklanni** [comment] 2015-10-16 22:19
@Ahrengot any luck?

**Closed** 2015-11-19 18:07 UTC
